// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxunfnqycxbnkeclvlwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4dW5mbnF5Y3hibmtlY2x2bHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTAyNTEsImV4cCI6MjA3MzUyNjI1MX0.DZ2V2peFm7Ga0KpGPe9agjp6GkdPWIdMZVXh4X7GNIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});